### ISSUE TITLE
how to update this ens pltforms

### ISSUE THREAD

**Issue by appledesire** [appledesire/ENS-platform#1]

**Comment by honest888** [comment]
You can download it from github.

**Comment by appledesire** [comment]
> 

This

**Comment by appledesire** [comment]
> You can download it from github.

This solution works! thanks.

**Comment by appledesire** [comment]
this doesn't work.

**Comment by honest888** [comment]
It will work.

**Comment by appledesire** [comment]
This answer solves the issue. Thank you!

**Comment by appledesire** [comment]
This answer solves the issue. Thank you!
